using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace TeamExamProject.Data;

/// <summary>
/// Идемпотентные SQL-правки на случай рассинхрона <c>__EFMigrationsHistory</c> и реальной схемы PostgreSQL
/// (миграция в истории есть, DDL не выполнялся).
/// </summary>
public static class DatabaseSchemaRepair
{
    public static async Task ApplyAsync(AppDbContext dbContext, ILogger logger, CancellationToken cancellationToken = default)
    {
        await EnsureUsersProfileColumnsAsync(dbContext, logger, cancellationToken);
        await EnsureAssignmentsTableAsync(dbContext, logger, cancellationToken);
        await EnsureAssignmentLeagueColumnsAsync(dbContext, logger, cancellationToken);
    }

    private static async Task EnsureUsersProfileColumnsAsync(
        AppDbContext dbContext,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        await dbContext.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "AcademicGroupLabel" character varying(100) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        try
        {
            await dbContext.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "Users" ALTER COLUMN "AvatarUrl" TYPE text;
                """,
                cancellationToken);
        }
        catch (PostgresException ex)
        {
            logger.LogWarning(ex, "Could not alter Users.AvatarUrl to text (may already be text). SqlState={SqlState}", ex.SqlState);
        }
    }

    private static async Task EnsureAssignmentsTableAsync(
        AppDbContext dbContext,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await dbContext.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "Assignments" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Title" character varying(200) NOT NULL,
                    "Description" character varying(4000) NOT NULL,
                    "DeadlineLabel" character varying(64) NOT NULL,
                    "DeadlineUtc" timestamp with time zone NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "IsAvailableInFeed" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW()
                );
                CREATE INDEX IF NOT EXISTS "IX_Assignments_IsActive" ON "Assignments" ("IsActive");
                CREATE INDEX IF NOT EXISTS "IX_Assignments_IsAvailableInFeed" ON "Assignments" ("IsAvailableInFeed");
                CREATE INDEX IF NOT EXISTS "IX_Assignments_DeadlineUtc" ON "Assignments" ("DeadlineUtc");
                ALTER TABLE "Assignments" ADD COLUMN IF NOT EXISTS "Tag" character varying(64) NOT NULL DEFAULT '';
                ALTER TABLE "Assignments" ADD COLUMN IF NOT EXISTS "LeagueTier" character varying(16) NOT NULL DEFAULT 'pro';
                CREATE INDEX IF NOT EXISTS "IX_Assignments_LeagueTier" ON "Assignments" ("LeagueTier");
                """,
                cancellationToken);
        }
        catch (PostgresException ex)
        {
            logger.LogWarning(ex, "Could not ensure Assignments table. SqlState={SqlState}", ex.SqlState);
        }
    }

    private static async Task EnsureAssignmentLeagueColumnsAsync(
        AppDbContext dbContext,
        ILogger logger,
        CancellationToken cancellationToken)
    {
        try
        {
            await dbContext.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE "Assignments" ADD COLUMN IF NOT EXISTS "Tag" character varying(64) NOT NULL DEFAULT '';
                ALTER TABLE "Assignments" ADD COLUMN IF NOT EXISTS "LeagueTier" character varying(16) NOT NULL DEFAULT 'pro';
                CREATE INDEX IF NOT EXISTS "IX_Assignments_LeagueTier" ON "Assignments" ("LeagueTier");
                """,
                cancellationToken);
        }
        catch (PostgresException ex)
        {
            logger.LogWarning(ex, "Could not ensure Assignments league columns. SqlState={SqlState}", ex.SqlState);
        }
    }
}
